In [2]:
import os
import pandas as pd

This notebook compares the ANN methods:

- method0: sorted interaction search
- method1: naive interaction search

It is refered to in the Chapter "Test Cases & Benchmarking Methodology". The faster of the two (method1) was used in the final comparison with the other search methods.


## Read data and cleanup
Raw results files can be found in sph-nearest-neighbor/test/results/

In [14]:
statsfile_fr_ann1 = os.path.join(resultsdir, "stats_fr_ann_method1.csv")
statsfile_fr_ann0 = os.path.join(resultsdir, "stats_fr_ann_method0.csv")

Read data and label search method, cleanup the fill, only keep relevant data, and combine to a single dataframe:

In [15]:
df_ann0 = pd.read_csv(statsfile_fr_ann0)
df_ann0 = df_ann0.assign(method=pd.Series(["ANN"]*len(df_ann0)).values)
df_ann1 = pd.read_csv(statsfile_fr_ann1)
df_ann1 = df_ann1.assign(method=pd.Series(["ANN"]*len(df_ann1)).values)

# set filltype to a nice integer percentage
df_ann0['fill'] = df_ann0.fill.mul(100).astype(int);
df_ann1['fill'] = df_ann1.fill.mul(100).astype(int);


# drop unused columns from dataframes
df_ann0.drop(columns=["time", "sizex", "sizey", "sizez"], inplace = True)
df_ann1.drop(columns=["time", "sizex", "sizey", "sizez"], inplace = True)

# combine to a single df
df = pd.concat([df_ann0, df_ann1])

## compare ANN method0 (sorted interaction search) and method1 (naive interaction search)

In [19]:
df[df['method'] == "ANN"].groupby(["fill","filltype","listmethod"])["tprocessing"].describe()

                           count        mean         std        min  \
fill filltype  listmethod
2    corners   0             5.0    63.17064    0.673018    62.2415
               1             5.0    34.76754    0.756158    33.6308
11   clusters2 0             5.0   791.79280    7.856341   786.8320
               1             5.0   452.38800   16.671359   426.5000
     clusters4 0             5.0   441.35580    3.963555   435.7760
               1             5.0   255.27260    9.156022   241.6570
     clusters6 0             5.0   223.46020    1.279870   222.4380
               1             5.0   138.88760    5.465991   131.3300
     corners   0             5.0  1339.17800    3.740217  1335.1800
               1             5.0   883.22400  285.427161   748.5450
     diagonal  0             5.0  1170.92200    5.504350  1165.2400
               1             5.0   615.41520   13.071465   603.9460

                                 25%        50%        75%        max
fill filltype  listmethod
2    corners   0             62.8041    63.3777    63.4160    64.0139
               1             34.4992    34.9827    35.0721    35.6529
11   clusters2 0            786.8630   787.6390   792.4080   805.2220
               1            445.5730   458.8730   463.3340   467.6600
     clusters4 0            439.5430   441.5900   443.7640   446.1060
               1            251.8710   256.0700   261.6220   265.1430
     clusters6 0            222.9050   222.9720   223.3040   225.6820
               1            136.0780   140.5340   140.6250   145.8710
     corners   0           1335.7800  1339.4500  1341.5200  1343.9600
               1            751.6930   754.7760   767.4560  1393.6500
     diagonal  0           1166.3700  1169.7900  1175.5300  1177.6800
               1            604.4100   611.9410   621.9840   634.7950

The processing time with method1 is about half that of method2, while memory use is comparable.

In [20]:
df[df['method'] == "ANN"].groupby(["fill","filltype","listmethod"])["memory"].describe()

                           count     mean        std      min      25%  \
fill filltype  listmethod
2    corners   0             5.0  16020.0  52.153619  15940.0  15996.0
               1             5.0  15921.6  74.543947  15864.0  15868.0
11   clusters2 0             5.0  42455.2  77.686550  42332.0  42448.0
               1             5.0  42427.2  48.033322  42344.0  42428.0
     clusters4 0             5.0  34302.4  40.159681  34232.0  34312.0
               1             5.0  34229.6  43.598165  34196.0  34204.0
     clusters6 0             5.0  27532.8  96.556719  27400.0  27472.0
               1             5.0  27540.8  56.384395  27444.0  27544.0
     corners   0             5.0  51009.6  86.236883  50908.0  50972.0
               1             5.0  51060.0  52.839379  51016.0  51028.0
     diagonal  0             5.0  48746.4  80.478569  48652.0  48668.0
               1             5.0  48768.0  45.869380  48712.0  48752.0

                               50%      75%      max
fill filltype  listmethod
2    corners   0           16044.0  16052.0  16068.0
               1           15872.0  15984.0  16020.0
11   clusters2 0           42456.0  42504.0  42536.0
               1           42452.0  42452.0  42460.0
     clusters4 0           34312.0  34328.0  34328.0
               1           34204.0  34244.0  34300.0
     clusters6 0           27564.0  27584.0  27644.0
               1           27560.0  27568.0  27588.0
     corners   0           50980.0  51056.0  51132.0
               1           51040.0  51068.0  51148.0
     diagonal  0           48780.0  48812.0  48820.0
               1           48756.0  48784.0  48836.0